package api

import (
	"context"
	"net/http"

	"github.com/google/uuid"
)

var xRequestID = http.CanonicalHeaderKey("X-Request-Id")

// RequestIDKey is the key that holds the unique request ID in a request context.
const RequestIDKey int = 0

// RequestIDMiddleware is a middleware that injects a request ID into the context of each
// request. A request ID is a string generated by Google lib: github.com/google/uuid
func RequestIDMiddleware(next http.Handler) http.Handler {
	fn := func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()
		requestID := r.Header.Get(xRequestID)
		if requestID == "" {
			requestID = uuid.New().String()
		}
		ctx = context.WithValue(ctx, RequestIDKey, requestID)
		next.ServeHTTP(w, r.WithContext(ctx))
	}
	return http.HandlerFunc(fn)
}

// GetReqID returns a request ID from the given context if one is present.
// Returns the empty string if a request ID cannot be found.
func GetReqID(ctx context.Context) string {
	if ctx == nil {
		return ""
	}
	if reqID, ok := ctx.Value(RequestIDKey).(string); ok {
		return reqID
	}
	return ""
}
